spring:
  datasource:
    hikari:
      username: sa
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type : trace